# Generated by Django 5.1.2 on 2024-11-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiasAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', models.TextField(blank=True, help_text='The article text submitted for bias analysis.', null=True)),
                ('groq_feedback', models.TextField(blank=True, help_text='Feedback provided by the Groq API.', null=True)),
                ('sambanova_feedback', models.TextField(blank=True, help_text='Feedback provided by the SambaNova API.', null=True)),
                ('combined_feedback', models.TextField(blank=True, help_text='Consolidated feedback from both APIs.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
